GPN_CSGK_WSDL:

TFHUB_CACHE_DIR:
TRANSFORMERS_CACHE:  #path to hugging face cache dir


GPN_DB_NAME: 'gpn'
GPN_DB_HOST: '192.168.10.36'
GPN_DB_PORT: 27017

BASE_MODEL_URL: "https://storage.googleapis.com/az-nlp/elmo_ru-news_wmt11-16_1.5M_steps.tar.gz"

MLFLOW_URL: "http://192.168.10.38:5000"

MLFLOW_ANALYSER_MODEL_NAME: "Analyser"
MLFLOW_ANALYSER_MODEL_STAGE: "Staging" #"Production" #or Staging.. refer ml flow docs for values

MLFLOW_CLASSIFIER_MODEL_NAME: "practice-classifier-ruRoberta-large"
MLFLOW_CLASSIFIER_MODEL_STAGE: "Staging"


#GPN_DB_USER: None # set in env, because it is secret
#GPN_DB_PASSWORD: None # set in env, because it is secret
#GPN_USE_MONGO_TLS: False # set in env, because it is secret
#GPN_DB_TLS_CA: None # set in env, because it is secret
#GPN_DB_TLS_KEY:  # set in env, because it is secret


#GPN_CURRENCY_USER  # set in env, because it is secret
#GPN_CURRENCY_PASSWORD  # set in env, because it is secret

#GPN_CSGK_USER # set in env, because it is secret
#GPN_CSGK_PASSWORD # set in env, because it is secret

GPN_CURRENCY_URL: #conversion rates service endpoint

#email
GPN_SMTP_SERVER:
GPN_SMTP_PORT:
GPN_SENDER_EMAIL:
#GPN_SENDER_LOGIN # set in env, because it is secret
#GPN_SENDER_PASSWORD # set in env, because it is secret
GPN_WEB_URL:


GPN_CLASSIFIER_EMAIL:
#GPN_CLASSIFIER_LOGIN # set in env, because it is secret
#GPN_CLASSIFIER_PASSWORD # set in env, because it is secret
