name: train-my-model

on: [push]

jobs:
  train:
    runs-on: [self-hosted, cml, gpu]

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        run: |
          echo 'Hi from CML @ nemo' >> report.md
          
          python --version >> report.md
          
          pip3 install /distr/tensorflow-2.5.0-cp36-cp36m-linux_x86_64.whl
          python -c "import tensorflow as tf; print(tf.__version__)" >> report.md
          
          pip3 install -r requirements.txt
          python check_db.py >> report.md          
          python train.py 
          cml-send-comment report.md

